### ISSUE TITLE
Delete Jenis Surat dengan Relasi FK

### ISSUE THREAD

**Issue by endymuhardin** [idtazkia/aplikasi-dosen#11]
Terjadi constraint violation pada saat menghapus Jenis Surat yang sudah direlasikan dengan Surat Tugas. 
Constraint violation no problem, memang seharusnya begitu. 
Tapi tetap harus dilakukan pengecekan apakah jenis tersebut sudah dipakai di surat, dan kalau sudah dipakai, berikan pesan error.

**Comment by addins** [comment]
saya coba perbaiki ya pak
